//
// Created by kenneth on 17/9/20.
//

#ifndef TAREA1_SISTEMASOPERATIVOS_HOSTSOCKET_H
#define TAREA1_SISTEMASOPERATIVOS_HOSTSOCKET_H
execute_socket_host();
#endif //TAREA1_SISTEMASOPERATIVOS_HOSTSOCKET_H
